# Generated by Django 2.2 on 2020-08-12 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200805_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 15, 51, 37, 985781, tzinfo=utc)),
        ),
    ]
